cognitedata/neat

- cognite/neat/explorer/explorer.py
- tests/api/conftest.py
- tests/api/memory_cognite_client.py
- tests/api/test_workflows.py
- tests/api/test_workflows/default_workflow.yml
Runs the default workflow and intercepts all CDF calls (assuming only assets, relationships, and labels), and dumps the resulting resources. The tests checks that it is the same resources that are created each time the test runs.
This is no change of functionality, so no bump or changelog
> Workflow Approval Tests

- cognite/neat/core/loader/graph_store.py
- cognite/neat/examples/workflows/fast_graph/workflow.yaml
- tests/api/test_workflows.py
- tests/api/test_workflows/fast_graph_workflow.yml
- tests/api/test_workflows/sheet2cdf_workflow.yml
- tests/test_package.py
No need to bump, only additional testing. 
* Check all versions match, including changelog and makefile.
* Approval test of `fast_graph` and `sheet2cdf`.
Wait with merging, the `fast_graph` workflow fails:
```
2023-05-12 17:09:05.540 ERROR    Step configuring_stores failed with error : Traceback (most recent call last):
File "C:\Users\MyUser\neat\cognite\neat\core\workflow\base.py", line 214, in run_step
new_flow_message = method(flow_message)
^^^^^^^^^^^^^^^^^^^^
File "C:\Users\MyUser\neat\tests\api\data\workflows\fast_graph\workflow.py", line 88, in step_configuring_stores
self.source_graph.init_graph(
File "C:\Users\MyUser\neat\cognite\neat\core\loader\graph_store.py", line 115, in init_graph
raise e
File "C:\Users\MyUser\neat\cognite\neat\core\loader\graph_store.py", line 105, in …
```
> Extended testing

- cognite/neat/core/extractors/rdf_to_assets.py
Assets API recommends(insists in the future versions) to use at most 10 partitions to list assets.
But for 99% of use cases even this number is too much and just creates unnecessary concurrent requests spikes.
Example: Mean asset list request latency is about 300ms => ~ 3rps, each request returns up to 1K items. So with 10 partitions, the throughput is 30K assets per second. >1.5M assets per minute. We have quite small number (<20) of projects across all clusters where the full assets set is bigger than 2M.
> CDF-18787: Use 2 partitions to list assets by default.

- cognite/neat/rules/_importer/_dms2rules.py
- cognite/neat/rules/models/_rules/_types.py
- cognite/neat/rules/models/_rules/dms_architect_rules.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
Three changes to better cover all DMS possibilities:
1. The ValueType of the DMS rules sheet is now parsed as a `ViewEntity` if the relation column is set. This means we now support referring to views which are in a different space than the default set in the metadata sheet, and an arbitrary version.
The next are more esoteric, less important, but gives us a better cover of DMS rules
1. A property can now be used in multiple indexes. 
2. A property can now be part om multiple uniqueness constraints. 
3. A container can have a required constraint on multiple other containers.
> [NEAT-28] Extend DMS rules to lists

- cognite/neat/rules/exporters/_base.py
- docs/config.yaml
Two fixes
* CDFExporter is a type of BaseExporter
* It looks like the example `config.yaml` have a real secret. Make it clear that this is fake
> fix: interface of Base/CDF Exporter

- cognite/neat/rules/exporters/_base.py
- cognite/neat/rules/exporters/_rules2excel.py
- cognite/neat/workflows/examples/Validate Rules/workflow.yaml
- cognite/neat/workflows/steps/lib/rules_exporter.py
* Add `output_role` parameter `Excelporter` such that the user can chose a different output than the input format.
* Added this as as a new configuration to the step.
* Extended the `ValidationRules` with a conversion step.
> [NEAT-31] Conversion workflow

- cognite/neat/rules/models/_rules/dms_architect_rules.py
- tests/tests_integration/test_rules/test_exporters/test_dms_exporters.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
**This needs be done after** #321  
In addition, to all these less related PRs.
Merge after #315 #316 #317 #318 #319 
This adds the filters to the views that are created. This is not yet exposed to the user as something they can set. Moving that for a separate task. 
We are potentially in trouble on this one. It seem like you cannot populate node type in transformations, which is why the the test is failing. Ref https://cognitedata.slack.com/archives/C0654Q63B6H/p1710667747367909
Reverted filter to only set explicitly the HasData filter that will be implicitly set when you create the filter anyways. Lets push on the data onboarding team to implement node type support.
> [NEAT-48] Create view filters

- cognite/neat/rules/issues/dms.py
- cognite/neat/rules/models/_rules/dms_architect_rules.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
Adds `Filter` column that can be either `hasData`, `nodeType`, or `hasData,nodeType`. 
Starting intentionally with minimum of filters supported, lets instead wait for people to request more before we add it.
> [NEAT-115] Add support for node type

- .github/workflows/code-quality.yaml
- pyproject.toml
Removed the integration tests from the regular test job and only run it on the coverage instead. 
Reason is that when we run 3.10 and 3.12 in parallel the integration tests could easily (and is already) interfering with each other. Now we only run integration tests once.
> [NEAT-107] Setup coverage job

- cognite/neat/rules/exporters/_base.py
- cognite/neat/rules/exporters/_rules2dms.py
- cognite/neat/rules/exporters/_rules2ontology.py
- cognite/neat/rules/exporters/_rules2yaml.py
- cognite/neat/rules/models/_rules/dms_schema.py
**Problem**: By default, when `Python` write to file it uses the default line endings of the OS system. This leads to problem when using neat to generate data models which are checked into Git history, as two users with different OSes, will get a massive diff due to the line endings.
**Suggested solution**: Neat is opinionated about the line endings (and encodings) to ensure consistent user experience between different OSes.
**Why hide it?** On the importers this is a hidden configuration (private class attribute). The reason for this is that importers are made for the most basic user that should not try to change this. However, in an edge case when someone wants to change it, they can although with no guarantee from **NEAT** that it will continue to work :)
> [NEAT-156] Line endings

- cognite/neat/rules/models/_rules/dms_architect_rules.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
**Problem** When referencing the edge.type should be set to the original type. This is not happening.
Here is the manual fixe needed in the customer project when trying to build a solution model and reuse a multiedge property, 
and being surprised when no edges showed up.
> [NEAT-177] Reference edge type

- cognite/neat/rules/importers/_spreadsheet2rules.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
This is a pure refactor to prepare for #378 
**Problem** Current implementation of `ExceImporter` reads a sheets with a reference model and instantiate a `Rule` object for `Reference` and one for `User` rules. When you start to add validation when `schema=extended` this triggers validation on instantiation of the User Rule object and fails because the User rules without reference set it fails.
**Solution** This gather the data from `Reference` and `User` rules and creates a single `dict` that is used to instantiate a `Rule` object for the user rules this time with the `reference` set. 
**In addition** Removing some unused test data
> [Preperation for NEAT-154] Refactor excel importer to do one instantiation.

- cognite/neat/rules/exporters/_rules2dms.py
- docs/CHANGELOG.md
Turns out it was already implemented but not exposed in the `DMSExporter`
> [NEAT-209] DMSExporter Support skipping node_types

- cognite/neat/rules/models/entities.py
- tests/tests_unit/rules/test_models/test_entities.py
* There is a lot of repeated code in the current Entities. 
* This implementation split parsing from validation. This enables us to have Warnings instead of Errors, ref NEAT-59, NEAT-79.
* This implementation has the logic in the base `Entity` class, with relatively easy extensions.
> [NEAT-183] Refactor entities

- cognite/neat/rules/importers/_base.py
- cognite/neat/rules/issues/base.py
- cognite/neat/rules/models/dms/_rules.py
- cognite/neat/rules/models/dms/_validation.py
- tests/tests_unit/rules/test_models/test_dms_architect_rules.py
A pure move off all the `@model_validator(mode="after")` validation in the `DMSRules`. 
There will be another round of refactoring of the methods in the new `DMSPostValidation`, but waiting with that to a separate PR, as that will also depend on the new `last` field introduced in #440 .
> [NEAT-227] Gather DMS Validation 🧹

- .pre-commit-config.yaml
- cognite/neat/app/api/routers/rules.py
- cognite/neat/graph/extractors/_mock_graph_generator.py
- cognite/neat/legacy/graph/extractors/_mock_graph_generator.py
- cognite/neat/legacy/rules/models/rules.py
- cognite/neat/rules/models/information/_rules.py
- tests/tests_legacy/tests_rules/test_rdfpath.py
Removed all linters that were already checked by ruff.
> [NEAT-378] 💣 Removed superfluous linters

- cognite/neat/rules/importers/__init__.py
- cognite/neat/rules/importers/_imf2rules/__init__.py
- cognite/neat/rules/importers/_imf2rules/_imf2classes.py
- cognite/neat/rules/importers/_imf2rules/_imf2metadata.py
- cognite/neat/rules/importers/_imf2rules/_imf2properties.py
- cognite/neat/rules/importers/_imf2rules/_imf2rules.py
- cognite/neat/workflows/steps/lib/current/rules_importer.py
A new step for importing rules has been added. The step converts
Information Modelling Framework (IMF) types, given as SHACL shapes,
into rules.
The new importer follows the compliance rules set by the OWL Importer,
but most of the logic are, in this case, included the SPARQL queries.
However, the validation checks are kept to ensure conformance.
The IMF identifiers are given as UUIDs, but CDF does not allow identifiers
starting with a number. All the relevant identifiers are therefore prefixed
with "IMF_"
IMF - attributes are properties that are described with several triples.
An attribute contains relations to reference data describing the meaning
of the attribute, as well as potential qualifiers and units of measure.
To ensure that this information is included the attributes are …
> feat: Add IMF rules importer

- cognite/neat/rules/_shared.py
- cognite/neat/rules/exporters/_base.py
- cognite/neat/rules/exporters/_rules2dms.py
- cognite/neat/rules/exporters/_rules2excel.py
- cognite/neat/rules/exporters/_rules2ontology.py
- cognite/neat/rules/exporters/_rules2yaml.py
- cognite/neat/rules/importers/_base.py
- cognite/neat/rules/importers/_dms2rules.py
- cognite/neat/rules/importers/_dtdl2rules/dtdl_importer.py
- cognite/neat/rules/importers/_rdf/_imf2rules/_imf2rules.py
- cognite/neat/rules/importers/_rdf/_inference2rules.py
- cognite/neat/rules/importers/_rdf/_owl2rules/_owl2rules.py
- cognite/neat/rules/importers/_spreadsheet2rules.py
- cognite/neat/rules/importers/_yaml2rules.py
- cognite/neat/rules/transformers/_base.py
- cognite/neat/workflows/steps/lib/current/rules_exporter.py
Went with `RulesTransformation` instead of `ModelTransformation` to make it clear that it should be used with Rules.
Did a renaming of the `Rules` alias to `VerifiedRules`, such that I could introduce `InputRules` and `Rules` for the combination of the two.
> [NEAT-389] 🏗Introduce rules transformation

- cognite/neat/rules/models/dms/_exporter.py
Turns of the docs were wrong, but the implementation is correct. So cleaned up the implementation a little bit taking advantage of the new reverse entity.
> [NEAT-409] 🧑‍🔧 DMS exporter handling of reverse prop

- cognite/neat/constants.py
- cognite/neat/graph/extractors/_classic_cdf/_base.py
- cognite/neat/graph/extractors/_mock_graph_generator.py
- cognite/neat/issues/_base.py
- cognite/neat/issues/warnings/__init__.py
- cognite/neat/issues/warnings/_properties.py
- cognite/neat/rules/importers/_rdf/_inference2rules.py
- tests/data/low-quality-graph.ttl
- tests/tests_unit/graph/test_loaders/test_dms_loader.py
- tests/tests_unit/rules/test_importers/test_inference_importer.py
- Handling use case with property which type cannot be determined due to missing node in the graph
- Added Ill formed graph that can be used to build up graph analysis module to spot for example the above use case
> Neat 411 inference handling properties which point to non existing nodes

- cognite/neat/issues/_base.py
- cognite/neat/rules/exporters/_rules2excel.py
- cognite/neat/rules/models/__init__.py
- cognite/neat/rules/models/_base_input.py
- cognite/neat/rules/models/_base_rules.py
- cognite/neat/rules/models/dms/_rules.py
- cognite/neat/rules/models/dms/_serializer.py
- cognite/neat/rules/models/domain.py
- cognite/neat/rules/models/entities/_single_value.py
- cognite/neat/rules/models/information/_rules.py
- cognite/neat/rules/models/information/_serializer.py
- cognite/neat/rules/models/information/_validation.py
- cognite/neat/rules/transformers/_converters.py
- cognite/neat/store/_base.py
- tests/tests_integration/test_rules/test_exporters/test_dms_exporters.py
- tests/tests_unit/rules/test_analysis.py
- tests/tests_unit/rules/test_exporters/test_rules2dms.py
- tests/tests_unit/rules/test_importers/test_dms_importer.py
- tests/tests_unit/rules/test_models/test_asset_rules.py
- tests/tests_unit/rules/test_models/test_dms_rules.py
- tests/tests_unit/rules/test_models/test_information_rules.py
- tests/tests_unit/rules/test_models/test_input_rules.py
- tests/tests_unit/rules/test_models/test_partial_information_rules.py
- tests/tests_unit/rules/test_models/test_wrapped_entities.py
* Rename `SheetEntity` to `SheetRow` to more descriptive of what this is reprensenting.
* Rework `SheetList` this is now an actual Python list and thus gets all methods for free. Implemented custom `pydantic` schema such that it can be used with `pydantic`. This avoids the clumsy `data` property.
* Removed unused methods/functions I found in the process.
> [NEAT-419] 🐳 Cleanup serialization Part 1

- cognite/neat/rules/models/_base_rules.py
- cognite/neat/rules/models/dms/_rules.py
- cognite/neat/rules/models/entities/_single_value.py
- cognite/neat/rules/models/information/_rules.py
- docs/CHANGELOG.md
- tests/tests_unit/rules/test_models/test_base_rules.py
Multiple sources for the bug
1. In verified rules, only SheetRows were stripped not metadata sheets. Fixed by moving validator to appropriate location.
2. Input rules creates entities, and entities does not strip extra spaces. Fixed by stripping whitespace from entities.
3. Field validators in child classes have precedence over parent classes (new learning for me), so need to strip in the Enum conversion methods.
> [NEAT-439] 🐛Strip cells

- cognite/neat/graph/extractors/_iodd.py
- Fixed time series external IDs so that they do not have URLI prefix
- Changed separator in time series external ids from "_" to "."
- Added method to IODDExtractor for extracting time series information to be used in separate script for enhancing time series with more information while better support for time series creation from knowledge graph is in place.
> Iodd extractor tweaks

- tests/tests_unit/rules/test_models/test_rdf_paths.py
These seems to have been lost in a cleanup, adding them back in as they are useful (at least to understand the syntax)
> 😕Added back missing tests

- cognite/neat/issues/_base.py
- cognite/neat/issues/errors/_external.py
- cognite/neat/issues/errors/_general.py
- cognite/neat/issues/errors/_properties.py
- cognite/neat/issues/errors/_resources.py
- cognite/neat/issues/errors/_workflow.py
- cognite/neat/issues/warnings/_external.py
- cognite/neat/issues/warnings/_general.py
- cognite/neat/issues/warnings/_models.py
- cognite/neat/issues/warnings/_properties.py
- cognite/neat/issues/warnings/_resources.py
- cognite/neat/issues/warnings/user_modeling.py
- docs/CHANGELOG.md
- tests/tests_unit/test_issues/test_issue_behavior.py
When you use a `contextmanager` to handle exceptions `RunTimeError` are mutated with setting the `__traceback__` attribute.
From the source code of the `contextlib` packages from the standard library
```python
....
except RuntimeError as exc:
if exc is value:
exc.__traceback__ = traceback # ⬅ This is causing the problem.
return False
except BaseException as exc:
if exc is not value:
raise
```
For example, all `ResourceError` in neat are `RunTimeError`s
1. We could avoid subclassing `RunTimeError` for all `NeatIssues`. 
2. Not make `NeatIssues` immutable.
I do not like solution 1 as it only solves this case. If the standard library of Python expects to mutate Exceptions, it seems very dangerous for us not to allow it. Thus, going with solution 2 means that since we have a hierarchy of …
> [NEAT-479] ☃ Frozen Instance bug

- cognite/neat/_session/_show.py
- cognite/neat/_store/_base.py
- docs/CHANGELOG.md
- Support for information rules and instance plotting in NeatSession
- Better plotting of rules for dms and information rules in NeatSession (accounts for `subClassOf` and `implements`)
> Neat 494 extend .show for information rules

- cognite/neat/_rules/models/dms/_rules.py
- cognite/neat/_rules/models/dms/_rules_input.py
- cognite/neat/_rules/models/information/_rules.py
- cognite/neat/_rules/models/information/_rules_input.py
- cognite/neat/_session/_base.py
- docs/CHANGELOG.md
> Shorter data model info

- cognite/neat/_session/_base.py
- cognite/neat/_session/_inspect.py
- cognite/neat/_session/_read.py
- cognite/neat/_store/_base.py
- docs/tutorials/data-onboarding/asset_hierarchy_migration.ipynb
- poetry.lock
- pyproject.toml
Updated first migration tutorial to use `NeatSession`. A few changes
* Added `neat.read.cdf.class.asset()` to read assets from classic CDF.
* Added `neat.inspect.properties` to return a DataFrame with all properties.
* Made the visualization of the instances account for being less than 6 types.
> [NEAT-500] Update migration tutorial Part 1

- cognite/neat/_constants.py
- cognite/neat/_issues/_base.py
- cognite/neat/_issues/errors/_resources.py
- cognite/neat/_issues/warnings/_models.py
- cognite/neat/_session/_base.py
- cognite/neat/_session/_inspect.py
- cognite/neat/_session/_state.py
> [NEAT-487] Aggegated view of issues

- cognite/neat/_session/_to.py
- docs/CHANGELOG.md
Can configure `neat.to.cdf.data_model` behavior for data model components that already exist in CDF
> Configure behaviour for data model components that already exist in cdf

- cognite/neat/_rules/importers/_dms2rules.py
- cognite/neat/_rules/models/dms/_exporter.py
- cognite/neat/_session/_base.py
- docs/CHANGELOG.md
- tests/data/windturbine.py
- tests/tests_unit/rules/test_importers/test_dms_importer.py
- When reading a data model from CDF, `inwards` edges are now treated as an edge with direction inwards and
not the reverse edge.
> [NEAT-511] ⬅ Inwards edges with properties

- cognite/neat/_issues/_base.py
- docs/CHANGELOG.md
- tests/tests_unit/test_issues/test_issue_behavior.py
```python
from cognite.neat import NeatSession
session = NeatSession(verbose=True)
session.read.excel("saputo_datamodel_v1.xlsx")
issues = session.verify()
print(issues.to_pandas())
```
leads to
Don't attempt to serialize the type of the issue by skipping private variables.
> [CDF-23143] 🐛 Issue serialization bug

- cognite/neat/_issues/__init__.py
- cognite/neat/_issues/_base.py
- cognite/neat/_issues/errors/_general.py
- cognite/neat/_rules/models/_types.py
- cognite/neat/_rules/transformers/_verification.py
- cognite/neat/_session/_base.py
- tests/tests_unit/test_issues/test_issue_behavior.py
This was caused by 2 things. 
1. We we not catching issues in `.conversion(...)`. This can happen when you have values that do not comply with DMS.
2. The `RegexError` lacked location making it hard to read.
> [NEAT-545] 🤗 Regex user experience

- cognite/neat/_graph/queries/_base.py
- cognite/neat/_session/_prepare.py
- docs/CHANGELOG.md
Before:
```
source = (URIRef("http://purl.org/cognite/neat/Activity"),
URIRef("http://purl.org/cognite/neat/workorderItemname"))
connection = "asset"
target = (URIRef("http://purl.org/cognite/neat/Asset"),
URIRef("http://purl.org/cognite/neat/wmtTagName"))
```
Now:
```
source = ("Activity","workorderItemname")
connection = "asset"
target = ("Asset","wmtTagName")
```
> Simplify make connection

- cognite/neat/_rules/models/dms/_exporter.py
- cognite/neat/_rules/models/dms/_rules.py
- cognite/neat/_rules/models/dms/_rules_input.py
- cognite/neat/_session/_state.py
- docs/CHANGELOG.md
- tests/tests_unit/rules/test_importers/test_excel_importer.py
- tests/tests_unit/rules/test_models/test_dms_rules.py
The issue of node filter warnings was already solved, but if you set a filter it was ignored. This fixes that. 
In addition, skips creating node types for all views as this is no longer necessary.
> [NEAT-521] 🤔Fix view filter

- cognite/neat/_rules/exporters/_rules2dms.py
- cognite/neat/_session/_to.py
- tests/tests_unit/test_session/test_to_yaml.py
This is not really ay bug. What happen is that when we stopped writing the Core model to cdf in `neat.to.cdf.data_model()` we stop exporting it in all other methods as well. It is better to have this explicitly set as a flag as it is clearer that we skip the core views + containers. And there are use cases when you want to dump these, to inspect them.
> [NEAT-587] 😏 Fix skip drop to views

- cognite/neat/_session/_base.py
- cognite/neat/_session/_read.py
- cognite/neat/_session/exceptions.py
- cognite/neat/_utils/auth.py
- docs/CHANGELOG.md
- docs/tutorials/data-onboarding/nordic44_onboarding.ipynb
**Note**: The user should not care about which version of the PySDK they are using. We always have a lower bound that enables all the functionality we need in neat.
**Open Question**: I made the `nordic44` a method instead of property. This is for consistency with other methods, but it is up for discussion. Note that the session wrapper that deals with errors do not handle properties.
> [NEAT-684] 🤗 Remove annoyance

- cognite/neat/_issues/warnings/__init__.py
- cognite/neat/_issues/warnings/_properties.py
- cognite/neat/_rules/importers/_rdf/_inference2rules.py
- docs/CHANGELOG.md
- tests/tests_unit/graph/test_loaders/test_dms_loader.py
- tests/tests_unit/rules/test_importers/test_inference_importer.py
It was a mistake to drop this one. It can for example be used in the information rules to set an alternative ID, similarly to have we now do for edges start and end node.
> [NEAT-672] 🤔 Not skip externalId in inference importer

- cognite/neat/_graph/loaders/_rdf2dms.py
- cognite/neat/_issues/warnings/_resources.py
- cognite/neat/_rules/transformers/_converters.py
- cognite/neat/_session/_base.py
- cognite/neat/_session/_fix.py
- cognite/neat/_session/_prepare.py
- cognite/neat/_session/_state.py
- cognite/neat/_session/_to.py
- docs/CHANGELOG.md
- tests/tests_unit/rules/test_models/test_information_rules.py
- [BREAKING] NeatSession.prepare.data_model.cdf_compliant_external_ids is moved under NeatSession.fix.data_model.cdf_compliant_external_ids
- [BREAKING] `cdf_compliant_external_ids` expects validated InformationRules as its input instead of InputRules
> Dm prepare steps on verified rules

- cognite/neat/_rules/transformers/__init__.py
- cognite/neat/_rules/transformers/_base.py
- cognite/neat/_rules/transformers/_converters.py
- cognite/neat/_rules/transformers/_mapping.py
- cognite/neat/_session/_base.py
- cognite/neat/_session/_create.py
- cognite/neat/_session/_inspect.py
- cognite/neat/_session/_mapping.py
- cognite/neat/_session/_prepare.py
- cognite/neat/_session/_set.py
- cognite/neat/_session/_show.py
- cognite/neat/_session/_state.py
- cognite/neat/_store/_graph_store.py
- cognite/neat/_store/_provenance.py
- cognite/neat/_store/_rules_store.py
- cognite/neat/_store/exceptions.py
- tests/tests_integration/test_session/test_data_model_to.py
- tests/tests_integration/test_session/test_graph_flow.py
- tests/tests_integration/test_session/test_read.py
- tests/tests_unit/graph/test_loaders/test_dms_loader.py
- tests/tests_unit/test_session/test_to_yaml.py
- tests/tests_unit/test_store/tests_rules_store.py
- tests/tests_unit/test_store/tests_rules_store/test_import_export.yml
Changes:
* RuleStore now has a provenance of type `RuleEntity`. This only has verified models, either info or info+dms.
* `.verify()` no longer has any effect. We can reintroduce it if we add support for keeping unverified model in the session.
**Note**: Removed pruning. As now only successful transformations moves the provenance forward.
Todo/discuss:
* Prefix transformer from unverified to verified.
* How to deal with manual transformations, i.e., importing when the rules store has rules in it.
> [NEAT-720, NEAT-722] 👫Information + DMS = True

- cognite/neat/_alpha.py
- cognite/neat/_rules/exporters/_rules2excel.py
- cognite/neat/_session/_to.py
- docs/CHANGELOG.md
This example shows result of command:
```
neat.to.excel("dm-redux.xlsx", include_properties="same-space")
```
> Export rules to excel with properties only from the same space as data model

- cognite/neat/_session/_to.py
- docs/CHANGELOG.md
> [NEAT-745] 🫵 feat; Support setting reference model directly

- cognite/neat/_graph/extractors/_classic_cdf/_base.py
- cognite/neat/_graph/extractors/_classic_cdf/_relationships.py
- cognite/neat/_graph/extractors/_classic_cdf/_sequences.py
- tests/tests_unit/graph/test_extractors/test_asset_extractor.py
This feature has never been exposed, and we decided it was a misstep thus removing it.
> [NEAT-796] 🤨 Remove unused feature to_type

- cognite/neat/_rules/analysis/_base.py
- docs/CHANGELOG.md
We are not plotting entire depth of data model implements (i.e. all the ancestors) when running method:
neat.show.data_model.implements()
The bug was caused when creating di-graph (networkx) from data model. We simply were too restrictive which nodes and edges should be added to di-graph. This has been now been fixed and full implements / inheritance is derived as expected.
Full implement depth is now being shown in visualization of data model in NeatSession
> 🕵️‍♂️ Neat 771 update ancestor plotting

- cognite/neat/_rules/transformers/_converters.py
- cognite/neat/_session/_set.py
- cognite/neat/_utils/text.py
- docs/CHANGELOG.md
- tests/tests_integration/test_session/test_graph_flow/test_aml_to_dms.yml
- tests/tests_integration/test_session/test_graph_flow/test_dexpi_to_dms.yml
- tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_to_python.yml
- tests/tests_unit/test_utils/test_text.py
Before when you set data model id, the display name of the old model was kept leading to confusion when deploying a model.
Now allow the user to set the display name, and if it is not set, it is generated based on the external ID of the model.
> [NEAT-796] 🤨 Display Name

- .github/pull_request_template.md
- .github/workflows/code-quality.yaml
- .github/workflows/release.yaml
- dev.py
Allow Improved header in changelog. In addition, no longer require a changelog entry when you select `skip` in the bump section.
**Note** Repeating the changelog from PR #1022 as that was not released due to the `Improved` header was not allowed. This is unlikely to happen in the future as a new check of the PR description will validate the bump and changelog entry. 
- The `neat.to.cdf.instances()` no longer loads CogniteAsset (and extensions) twice.
> 🤖 Allow Improved Header in Changelog.

- cognite/neat/_rules/models/entities/_wrapped.py
- tests/tests_unit/rules/test_models/test_wrapped_entities.py
See changelog below.
- Reading a data model with a view with an equals filter on a property no longer raises a `AttributeError: 'str' object has no attribute 'get'` error.
> 🐛 DMS Equals filter on property

- cognite/neat/_rules/models/dms/_validation.py
- tests/tests_integration/test_session/test_read.py
- Reading the `CogniteCore` model, `neat.read.examples.core_data_model()`, no longer give warnings.
> [NEAT-810] 😦 No warning from reading core

- cognite/neat/_session/_base.py
- cognite/neat/_session/_read.py
- cognite/neat/_session/_state.py
- cognite/neat/_store/_rules_store.py
- Give appropriate error messages if the user execute the `NeatSession` methods in the wrong order.
> [NEAT-734]🤼 Appropriate error message when user does illegal actions

- cognite/neat/_session/_base.py
- cognite/neat/_session/_template.py
- docs/reference/NeatSession/create.md
- docs/reference/NeatSession/template.md
- docs/tutorials/data-modeling/core_extension.ipynb
- docs/tutorials/data-onboarding/classic_knowledge_graph.ipynb
- tests/tests_end_to_end/test_rules_flow.py
- tests/tests_integration/test_session/test_create_enterprise.py
- tests/tests_integration/test_session/test_graph_flow.py
- tests/tests_integration/test_session/test_read.py
We realized that `create` is misleading, thus renaming this API to template as what we are creating is a template. For example `neat.template.solution_model(...)` reads more precisely what we are doing instead of `neat.create.solution_model(...)`. 
- [BREAKING] Renamed the `neat.create` to `neat.template`.
> [NEAT-823] 🧙‍♂️ Rename create to template

- cognite/neat/_rules/models/entities/_wrapped.py
- tests/tests_unit/rules/test_models/test_wrapped_entities.py
Caused by a naive use of regex. Replace it with startswith and endswith for more robust parsing. 
- Running `neat.read.cdf.data_model(...)` to fetch a data model no longer raises a `ValueError` if one of the views in the model contains a filter that uses a special characters such as `&`.
> [NEAT-852] 𓀎 Raw filter filter with special character fix.

- cognite/neat/_client/data_classes/schema.py
- tests/tests_unit/rules/test_models/test_dms_schema.py
Added an internal helper method to the `DMSSchema` that creates the schema from a read version of a data model. This is useful when we get model from a user and need this for debugging.
I used this one to hunt down the bug in #1059
> [prep NEAT-852]🕵🏼DMSSchema from read model

- cognite/neat/_store/_graph_store.py
Remote triplestore (running oxigraph on Docker) was not getting updated.
Context for reviewers: Remote triplestore is an experimental feature under development, not released. 
- Incorrect parameter "update_endpoint" when instantiating SPARQL Update store.
> fix: incorrect call when defining remote store

- .github/workflows/code-quality.yaml
We introduced the coverage test a year ago, and then I set a low threshold as we had a lot of uncovered code. Suggest we now increase it to 80% which is a good target for coverage.
> Ci: update coverage threshold

- cognite/neat/_rules/importers/_yaml2rules.py
- tests/data/__init__.py
- tests/data/_schema/physical_yamls/invalid_yaml.expected_issues.yaml
- tests/data/_schema/physical_yamls/invalid_yaml.yaml
- tests/tests_integration/test_api/test_validate_rules.py
Introducing a new test for checking the reading of DMS models. Found one small bug which I fixed.
- The `neat.read.yaml()` now gives a `FileReadError` if the yaml is invalid.
> [NEAT-868] 😇 Setup new test framework for validating DMS Rules

- .github/workflows/code-quality.yaml
Adding Python 3.13 to Python version matrix in CI build.
- Adding Python 3.13 to Python version matrix in CI build.
> add python 3.13 to ci build

- cognite/neat/_session/_template.py
- tests/tests_integration/test_session/test_graph_flow.py
Rename method for better understanding what it is doing
- Renamed `extension` to `expand`
> rename method from extension to expand

- cognite/neat/_session/_set.py
- tests/tests_integration/test_session/test_graph_flow.py
- tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_ids_to_python.yml
neat.set.data_model_id was not updating name of data model
- neat.set.data_model_id properly updated name of data model
> NEAT-900 Fix missing update of data model name via set.data_model_id

- cognite/neat/_session/_to.py
Sub-selection of schema components to be published to CDF does not work as expected in `neat.to.cdf.data_model()`. Accordingly this capability for time being will be removed from public method, since users can control what effect the method has via `existing` argument.
- Ability to fine-grain which component of schema is to be published to CDF
> Remove non-functional component selection

- cognite/neat/core/_graph/extractors/_classic_cdf/_files.py
- cognite/neat/session/_read.py
- tests/data/_instances/asset_centric_cdf/files.yaml
- tests/tests_unit/test_graph/test_extractors/test_files_extractor.py
- tests/tests_unit/test_session/test_read.py
In addition, added skipping of files that have `instanceId` set. These have a counterpart in DMS that should be ingested instead.
- Support for reading file metadata. `neat.read.cdf.classic.file_metdata(...)`
> [NEAT-924] 🗒Read Files

- cognite/neat/session/_read.py
This is a need for a case were the following `["無", "無し", "-"]` were used as empty values.
> [NEAT-960] 🗾 Allow user specified empty values

- cognite/neat/core/_data_model/models/dms/_validation.py
- cognite/neat/core/_issues/warnings/__init__.py
- cognite/neat/core/_issues/warnings/_properties.py
- tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.expected_issues.yaml
- tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.yaml
Unfortunately it is possible to deploy invalid models to CDF with reverse direct pointing direct relations that does not point in the opposite way
> ↩Fix reverse issue

- cognite/neat/core/_data_model/models/dms/_validation.py
- cognite/neat/core/_issues/warnings/__init__.py
- cognite/neat/core/_issues/warnings/_properties.py
- tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.expected_issues.yaml
- tests/data/_schema/physical_yamls/reverse_direct_relation_missing_target.yaml
Unfortunately it is possible to deploy invalid models to CDF with reverse direct pointing direct relations that does not point in the opposite way. This makes it impossible to read these models into CDF (and fix them). Thus replacing the error with a warning in the validation. 
- Reading a data model from CDF with `neat.read.cdf.data_model(...)` with a reverse direct relation that points to a direct relation that is not pointing in the opposite direction now gives a warning instead of an error.
> ↩Fix reverse issue (#1193)

- cognite/neat/core/_utils/text.py
- tests/tests_unit/test_utils/test_text.py
Numbers gets removed in the to_camel function.
> Fix naming Standaridzation

- pyproject.toml
- uv.lock
Currently optional dep. group is called `pyoxigraph`, however in our code base we refer to it as `oxi`. 
- Reverted the group name from `pyoxigraph` to `oxi`.
> Update pyproject.toml with right optional dependency group

- cognite/neat/core/_instances/loaders/_rdf2dms.py
- tests/tests_integration/test_session/test_graph_flow.py
CDF system (schema) space (e.g. cdm) does not contain definition of node types. This leads to error when we try to create instances with neat, as neat is automatically set node type for every instance , where node type has same id (space,external_id) of view instances is being written through. 
- When generating instances through views from system space(s) node type is no longer set
> Neat 1007 skip setting node type for instances of system space views

- cognite/neat/core/_client/_api/crud.py
- cognite/neat/core/_client/_api_client.py
- cognite/neat/core/_client/_deploy.py
- cognite/neat/core/_client/data_classes/deploy_result.py
- cognite/neat/core/_client/testing.py
- tests/tests_unit/test_neat_client/test_deploy.py
This introduces a deploy method. This method builds on a CrudAPI interface. It deals with the details of how to handle existing resources. It returns a detailed deploy result which I will use in future PRs to create a UX for displaying it.
> [prep NEAT-1018] Create shared deploy logic.

- cognite/neat/core/_store/_data_model.py
- tests/tests_unit/test_store/tests_rules_store.py
See below
- Running `neat.to.cdf.data_model()` no longer gives a `UnboundLocalError` if there is an error in the deployment.
> [NEAT-1115]  Unbound local error

- cognite/neat/core/_data_model/exporters/_data_model2excel.py
- tests/tests_unit/test_rules/test_exporters/test_rules2excel.py
Added a new **JSON** to the drop-down menu in Excel, allowing users to select it as a value type for properties of concepts and views
- Added **JSON** as a selectable option in the Excel drop-down menu.
> Add JSON option in drop-down of Excel

- cognite/neat/core/_data_model/_shared.py
- cognite/neat/core/_data_model/importers/_dict2data_model.py
- cognite/neat/core/_data_model/importers/_dms2data_model.py
- cognite/neat/core/_data_model/importers/_rdf/_base.py
- cognite/neat/core/_data_model/importers/_spreadsheet2data_model.py
- cognite/neat/core/_data_model/models/_import_contexts.py
- cognite/neat/core/_data_model/models/conceptual/_validation.py
- cognite/neat/core/_data_model/models/physical/_validation.py
- cognite/neat/core/_data_model/transformers/_converters.py
- cognite/neat/core/_issues/_contextmanagers.py
- cognite/neat/core/_issues/_factory.py
- cognite/neat/core/_store/_instance.py
- cognite/neat/core/_utils/auxiliary.py
`ImportedDataModel` is an internal data structure we use to import data models from different sources such as spreadsheet, CDF, ontologies and so on. We use the context today when the source is a spreadsheet to tell the user exactly which row have warnings/errors to make it easy for them to fix. This is similar to a `metadata` field used in the CDF API.
This PR changes the type of context from one that is only valid for a spreadsheet source to a more generic one. This is because in an upcoming PR we will use the context in a different importers that are not importing form spreadsheet, but for example a Graph or Ontology. Then we will use this context for different purposes.
> Generic context on Imported Data Model

- tests/tests_integration/test_client_available.py
Removing part of test that was used locally for debugging, which unft. got pushed and merged to main. This test is blocking all other PRs, who got synced with main. Therefore, the test is reverted to the original form, without the debug part.
- Reverted to the original test
> Removing debugging part of test

- .github/CODEOWNERS
The team has been renamed from accelerate to velocity. I have done this in two steps to ensure that the repo is not without owners:
1. Add Team velocity as code owner.
2. Remove accelerate team (This PR).
> 🙃 Remove accelerate team
