README.md
docs/index.md

Added pretty badges

---

cognite/neat/graph/loaders/rdf_to_dms.py
cognite/neat/rules/exporter/rules2pydantic_models.py
cognite/neat/rules/models.py
cognite/neat/workflows/steps/lib/graph_loader.py

Updates to generate FDM from RDF:
1) Function to add class name as prefix to instance external id (to ensure uniqueness if same external id is used across classes) 
2) Reduce default batch size when uploading nodes to 1000

Feature xid class prefix

---

cognite/neat/graph/loaders/core/rdf_to_assets.py
cognite/neat/graph/loaders/core/rdf_to_relationships.py
cognite/neat/graph/loaders/validator.py
cognite/neat/graph/stores/graph_store.py
cognite/neat/rules/exporter/rules2triples.py
cognite/neat/workflows/_exceptions.py
cognite/neat/workflows/steps/data_contracts.py
cognite/neat/workflows/steps/lib/graph_contextualization.py
cognite/neat/workflows/steps/lib/graph_extractor.py
cognite/neat/workflows/steps/lib/graph_loader.py
cognite/neat/workflows/steps/lib/graph_store.py
cognite/neat/workflows/steps/lib/graph_transformer.py
cognite/neat/workflows/steps/lib/io_steps.py
cognite/neat/workflows/steps/lib/rules_exporter.py
cognite/neat/workflows/steps/lib/rules_parser.py
cognite/neat/workflows/steps/step_model.py
cognite/neat/workflows/steps_registry.py
pyproject.toml

**Before**
In Workflows
```
Found 171 errors in 11 files (checked 1092 source files)
```
In total
```
Found 303 errors in 22 files (checked 1201 source files)
```
**After**:
In total
```
Found 130 errors in 11 files (checked 1201 source files)
```

Mypy Workflows Part 2

---

.pre-commit-config.yaml
cognite/neat/app/api/configuration.py
cognite/neat/app/api/data_classes/configuration.py
cognite/neat/app/api/routers/configuration.py
cognite/neat/app/api/routers/crud.py
cognite/neat/app/api/routers/data_exploration.py
cognite/neat/app/api/routers/rules.py
cognite/neat/app/api/routers/workflows.py
cognite/neat/app/api/utils/data_mapping.py
cognite/neat/app/monitoring/metrics.py
cognite/neat/exceptions.py
cognite/neat/graph/loaders/core/labels.py
cognite/neat/rules/exporter/rules2ontology.py
poetry.lock
pyproject.toml
tests/app/api/memory_cognite_client.py
tests/app/api/test_workflows.py

**Before**
```
Found 130 errors in 11 files (checked 1192 source files)
```
**After**:
```
0
```

MyPy Neat App

---

cognite/neat/rules/models/_rules/base.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/rules/models/_rules/dms_schema.py
tests/tests_unit/rules/test_models/test_dms_architect_rules.py
tests/tests_unit/rules/test_models/test_dms_schema.py
tests/tests_unit/rules/test_models/test_domain_rules.py
tests/tests_unit/rules/test_models/test_information_rules.py

First pass, needs another round to handle more edge cases. But this is already a big PR so saving that for later.

[NEAT-20] Validate Containers and Views

---

cognite/neat/rules/_importer/_base.py
cognite/neat/rules/_importer/_spreadsheet2rules.py
cognite/neat/rules/models/_rules/__init__.py
cognite/neat/rules/models/_rules/base.py
cognite/neat/utils/spreadsheet.py
tests/tests_unit/rules/conftest.py
tests/tests_unit/rules/importer/test_excel2rules.py
tests/tests_unit/rules/test_models/test_domain_rules.py
tests/tests_unit/rules/test_models/test_information_rules.py
tests/tests_unit/rules/test_models/utils.py

Added Spreadsheet importer
Added tests for new importer

Neat 22 update spreadsheet importer to work with profiled rules

---

cognite/neat/rules/models/_rules/_types/_base.py
cognite/neat/rules/models/_rules/_types/_field.py
cognite/neat/rules/models/_rules/_types/_value.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
tests/tests_unit/rules/test_models/test_dms_architect_rules.py

Neat 39 create dms2 infor arch rules converter

---

cognite/neat/rules/exporters/_rules2dms.py
cognite/neat/rules/models/_rules/_types/_base.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/utils/cdf_loaders.py
cognite/neat/utils/text.py

* In DMS exporter,  add option for `standardize_casing` which PascalCase views, containers externalIds and camelCase properties.

[NEAT-63] Casing DMS exporter

---

cognite/neat/rules/exporters/_rules2dms.py
cognite/neat/rules/importers/_dtdl2rules/dtdl_converter.py
cognite/neat/rules/importers/_dtdl2rules/dtdl_importer.py
cognite/neat/rules/models/_rules/_types/_base.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/utils/cdf_loaders.py
cognite/neat/utils/text.py

* Set prefix to the most common prefix in data instead of `neat` 
* Set title of data model to the name of the directory or zip file if importer is instansiated from directory or zip.

Style DTDL Importer

---

cognite/neat/rules/exporters/__init__.py
cognite/neat/rules/exporters/_rules2yaml.py
cognite/neat/rules/importers/__init__.py
cognite/neat/rules/importers/_yaml2rules.py
cognite/neat/rules/issues/fileread.py
cognite/neat/rules/issues/spreadsheet_file.py
tests/tests_unit/rules/test_exporters/test_rules2yaml.py

Realized that I might as well implement the Exporter as well as the importer.

[NEAT-89] YAML exporter/importer

---

docs/gettingstarted/installation.md
docs/terminology/graph.md
docs/terminology/rules.md
docs/tutorials/data-modeling-lifecycle/overview.md

- Added updated version of docs for Rules v2

updated docs

---

cognite/neat/rules/exporters/_rules2excel.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/rules/models/_rules/information_rules.py
cognite/neat/workflows/steps/lib/rules_importer.py
tests/tests_unit/rules/test_exporters/test_rules2excel.py

[NEAT-136] Exporting Reference Model

---

cognite/neat/rules/models/_rules/base.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/rules/models/_rules/information_rules.py

added extension field

---

cognite/neat/rules/models/_rules/_types/_value.py
cognite/neat/rules/models/_rules/dms_schema.py
tests/tests_unit/rules/test_exporters/test_rules2dms.py
tests/tests_unit/rules/test_models/test_dms_schema.py

Realized that the part using the SQL types, so added a test to ensure that the code was hit.

Move sql types

---

.github/workflows/code-quality.yaml
cognite/neat/exceptions.py

Automatically tries to fix linting issues by comitting any changes produced by running linting.
The commit shown below was automatically generated.

Auto fix linting

---

cognite/neat/rules/models/_rules/dms_architect_rules.py

This should be
`power:GeneratingUnit(propertry=name)`

Bugfix Reference

---

cognite/neat/graph/extractor/_graph_capturing_sheet.py
cognite/neat/rules/examples/power-grid-containers.yaml
cognite/neat/rules/examples/power-grid-model.yaml
cognite/neat/rules/exporter/_rules2dms.py
cognite/neat/rules/exporter/_rules2excel.py
cognite/neat/rules/exporters/_rules2excel.py
cognite/neat/rules/importer/_dms2rules.py
cognite/neat/rules/importers/_dms2rules.py
cognite/neat/rules/models/_rules/base.py
cognite/neat/rules/models/_rules/dms_architect_rules.py
cognite/neat/rules/models/_rules/dms_schema.py
cognite/neat/rules/models/_rules/domain_rules.py
cognite/neat/rules/models/_rules/information_rules.py
cognite/neat/utils/spreadsheet.py
poetry.lock
pyproject.toml
tests/data/IntegrationTestsImmutable-OSDUWells-1.yaml
tests/data/power-CapacityBid-containers.yaml
tests/tests_unit/rules/test_exporters/test_rules2yaml.py

Biggest change is that all container properties are now listable, so there are many extra checks that are no longer necessary.
Updating lead to some other changes as well.

Update cognite sdk

---

cognite/neat/rules/exporters/_rules2excel.py
cognite/neat/rules/models/dms/_converter.py
cognite/neat/rules/models/dms/_rules.py
cognite/neat/rules/models/dms/_schema.py
cognite/neat/rules/models/information/_converter.py
cognite/neat/rules/models/information/_rules.py

A tiny PR to add the new field `Last` to ensure we are aligned on what we are planning to do.
Splitting the refactoring work if using this new field into multiple PRs.

[NEAT-226] Introduce last 👋

---

cognite/neat/rules/models/information/_rules.py
cognite/neat/rules/models/information/_serializer.py
docs/CHANGELOG.md

- Moved serializer to dedicated module

Neat 256 create serializer module for information rules

---

docs/data-modeling-principles.md
mkdocs.yml

[NEAT-261] 🤴Data Modeling Principles 

---

cognite/neat/graph/loaders/__init__.py
cognite/neat/graph/loaders/_base.py
cognite/neat/graph/loaders/_rdf2dms.py
cognite/neat/graph/stores/_base.py
cognite/neat/rules/models/dms/_schema.py
tests/tests_unit/test_graph/test_loaders/test_rdf2dms.py

This is a first draft with the core skeleton of the DMS Loader
Moving to separate PR:
* Error handling
* Tracking of ingestion
* Writing to CDF
* Implement the `.as_read` method in the `DMSSchema`.
In addition, we already have a task on upgrading the store https://cognitedata.atlassian.net/browse/NEAT-279

[NEAT-95] 🚛Draft DMS Loader

---

mkdocs.yml

[NEAT-380]😁 feat: add favicon

---

cognite/neat/graph/loaders/_rdf2dms.py
cognite/neat/rules/transformers/_converters.py
tests/tests_unit/graph/test_loaders/test_dms_loader.py

- handling Uknown value type
- fix bug with listable direct relations

fix test and how unknown valuetypes are handled

---

cognite/neat/graph/loaders/_rdf2dms.py
cognite/neat/rules/transformers/_converters.py
tests/tests_unit/graph/test_loaders/test_dms_loader.py
tests/tests_unit/rules/test_models/test_dms_rules.py

- Allow for configurability of Info2DMS transformer to drop properties which contain unknown value types

Neat 415 updated information to dms

---

cognite/neat/graph/extractors/__init__.py
cognite/neat/graph/extractors/_classic_cdf/_assets.py
cognite/neat/graph/extractors/_classic_cdf/_base.py
cognite/neat/graph/extractors/_classic_cdf/_classic.py
cognite/neat/graph/extractors/_classic_cdf/_data_sets.py
cognite/neat/graph/extractors/_classic_cdf/_events.py
cognite/neat/graph/extractors/_classic_cdf/_files.py
cognite/neat/graph/extractors/_classic_cdf/_labels.py
cognite/neat/graph/extractors/_classic_cdf/_relationships.py
cognite/neat/graph/extractors/_classic_cdf/_sequences.py
cognite/neat/graph/extractors/_classic_cdf/_timeseries.py
cognite/neat/rules/models/entities/_single_value.py
cognite/neat/utils/collection_.py
docs/CHANGELOG.md
tests/tests_unit/graph/test_extractors/test_asset_extractor.py

Combining all extractors into one. Tested on PowerOps

[NEAT-423] 🤪Classic extractor

---

.github/workflows/prepare-release.yaml
dev.py

Need to merge to verify that this works, but it should produce an action that automatically does the bump and creates a prepare branch.

[NEAT-445] 🤓 Automate release process

---

cognite/neat/rules/transformers/__init__.py
cognite/neat/rules/transformers/_converters.py
docs/CHANGELOG.md

Added Rules transformer :
-    "MultiObjectTypeToUnknownType",
-   "MixedValueTypeToStringType",

Neat 397 handling of multi value types

---

cognite/neat/constants.py
cognite/neat/graph/queries/_base.py
cognite/neat/graph/transformers/__init__.py
cognite/neat/graph/transformers/_value_type.py
cognite/neat/rules/analysis/_information.py
cognite/neat/rules/models/information/_rules.py
docs/CHANGELOG.md
tests/tests_unit/graph/test_transformers/test_split_multi_value_property_transformer.py
tests/tests_unit/rules/test_importers/test_inference_importer.py

Graph transformer `SplitMultiValueProperty` which splits multi-value properties into separate properties with single value

Graph transformer multi value

---

cognite/neat/graph/transformers/_value_type.py
cognite/neat/rules/models/data_types.py
docs/CHANGELOG.md

- added support for decimal
- remove usage of `to_camel_case` in the transformer due to removal of characters if string has `_`

added support for decimal, fixed SplitMultiValueProperty

---

docs/tutorials/data-onboarding/knowledge_graph_migration.ipynb

Note yet linked in the docs as it is currently to far away from being finished.

[NEAT-455] Experimental notebook

---

cognite/neat/graph/queries/_base.py
cognite/neat/graph/transformers/__init__.py
cognite/neat/graph/transformers/_classic_cdf.py
tests/data/classic_windfarm.py
tests/tests_end_to_end/test_graph_flow.py
tests/tests_end_to_end/test_graph_flow/test_classic_to_dms.yml

Running into issues due to `RelationshipExtractor`: It does not link source_external_id and target_external_id as Entites, but instead uses literal for the external id.

[NEAT-467] 👫Relationships to Schema

---

cognite/neat/session/_read.py
cognite/neat/session/_wizard.py
tests/tests_end_to_end/test_rules_flow.py

- Added wizard for read.rdf()
- Added graph readers for Rules

added wizard

---

cognite/neat/_rules/_constants.py
cognite/neat/_rules/models/_types.py
cognite/neat/_rules/models/dms/_rules.py
cognite/neat/_session/_base.py
cognite/neat/_session/_prepare.py
cognite/neat/_session/_state.py
cognite/neat/_session/_to.py
cognite/neat/_session/_wizard.py
docs/terminology/rules.md

- added `prepare` endpoint
- added methods to push data model and instances to CDF
- Update docs to say that In Model is manadatory
- Fixed regex patterns 
- Addes specific types for data model external id and space (compliance with CDF API)

Session prepare

---

cognite/neat/_session/_base.py
cognite/neat/_session/_state.py
cognite/neat/_session/exceptions.py
docs/CHANGELOG.md

[NEAT-488]😎	 Session exceptions

---

cognite/neat/_session/_base.py
cognite/neat/_session/_read.py
cognite/neat/_store/_base.py
cognite/neat/_store/_provenance.py
docs/CHANGELOG.md

- `NeatSession.read.rdf.examples.nordic44`
- Improved session overview in UI

Neat 486 add neat.rdf.examples.nordic44

---

cognite/neat/_session/_prepare.py
cognite/neat/_session/_read.py
cognite/neat/_session/_show.py
cognite/neat/_session/_to.py
cognite/neat/_session/exceptions.py
docs/CHANGELOG.md

fix: error handling neat session

---

cognite/neat/_rules/transformers/__init__.py
cognite/neat/_rules/transformers/_converters.py
cognite/neat/_session/_base.py
cognite/neat/_session/_set.py
docs/CHANGELOG.md

[NEAT-502] Added  set operation to NeatSession

---

cognite/neat/_graph/loaders/_base.py
cognite/neat/_graph/loaders/_rdf2asset.py
cognite/neat/_graph/loaders/_rdf2dms.py
cognite/neat/_issues/__init__.py
cognite/neat/_issues/_base.py
cognite/neat/_rules/transformers/_verification.py
cognite/neat/_session/_base.py
cognite/neat/_session/_inspect.py
cognite/neat/_session/_state.py
cognite/neat/_session/_to.py
cognite/neat/_utils/upload.py
docs/CHANGELOG.md
tests/tests_unit/test_issues/test_issue_behavior.py

[NEAT-512, NEAT-513] 🧑‍🎨Catch warnings

---

cognite/neat/_constants.py
cognite/neat/_rules/importers/_spreadsheet2rules.py
cognite/neat/_rules/models/dms/_exporter.py
cognite/neat/_rules/models/dms/_rules.py
docs/CHANGELOG.md

`NEAT-518` and `NEAT-519` turned out to be the same issue reported twice. In addition, found one extra bug when reverse direct relation is referencing a parent view.

[NEAT-518, NEAT-519, NEAT-520] 🦖Multiple bugs

---

cognite/neat/_graph/loaders/_base.py
cognite/neat/_graph/loaders/_rdf2dms.py
cognite/neat/_session/_to.py
cognite/neat/_utils/auth.py
cognite/neat/_utils/upload.py
docs/CHANGELOG.md
tests/tests_integration/test_graph/test_loaders/test_dms_loader.py

🧐Unchanged issue

---

cognite/neat/_session/_base.py
cognite/neat/_utils/auxiliary.py
tests/tests_unit/test_session/test_meta.py
tests/tests_unit/test_utils/test_auxiliary.py

[NEAT-553]  🧑‍🌾Ensure primary types in Session parameters

---

cognite/neat/_session/_read.py
docs/CHANGELOG.md

Tested on large scale example:

[NEAT-560] 🏭 Read classic graph

---

cognite/neat/_rules/importers/_dms2rules.py
cognite/neat/_rules/models/dms/_rules_input.py
cognite/neat/_rules/models/dms/_schema.py
cognite/neat/_rules/models/entities/_single_value.py
cognite/neat/_session/_base.py
cognite/neat/_session/_read.py
cognite/neat/_session/_state.py
cognite/neat/_utils/cdf/loaders/_data_modeling.py
docs/CHANGELOG.md
tests/data/__init__.py
tests/data/referencing_core/MyDescribable.container.yaml
tests/data/referencing_core/MyDescribable.view.yaml
tests/data/referencing_core/enterprise.datamodel.yaml
tests/tests_end_to_end/test_rules_flow.py
tests/tests_integration/test_session/test_read.py

**Note** I think this solution can be improved if we move out the post validation outside `pydantic`. However, not sure about this, so that requires a discussion.

[NEAT-551] 🦭neat.verify Lookup in CDF

---

cognite/neat/_graph/transformers/_classic_cdf.py
cognite/neat/_rules/transformers/_converters.py
cognite/neat/_session/_base.py
cognite/neat/_session/_prepare.py
docs/CHANGELOG.md
tests/tests_integration/test_session/test_graph_flow.py
tests/tests_integration/test_session/test_graph_flow/test_classic_to_dms.yml

[NEAT-583]  🪜Conversion info DMS edges

---

cognite/neat/_rules/importers/_rdf/_inference2rules.py
docs/CHANGELOG.md
tests/tests_unit/rules/test_importers/test_inference_importer.py

- Inference, instances are ordered by no of properties
- Inference, if Unknown value is present in multivalue property it is dropped

🧠 Improve inference

---

cognite/neat/_rules/exporters/_rules2dms.py
cognite/neat/_session/_to.py
docs/CHANGELOG.md
tests/tests_integration/test_session/test_data_model_to.py

[NEAT-618] 👷 Model recreate round2

---

cognite/neat/_rules/importers/_dms2rules.py
docs/CHANGELOG.md
tests/data/windturbine.py

[NEAT-624] 🔬 Fix enum unique issue

---

cognite/neat/_session/engine/_load.py

💦Load Engine Cwd

---

cognite/neat/_session/_show.py
cognite/neat/_utils/io_.py
docs/tutorials/data-modeling/cold_start.ipynb
docs/tutorials/data-modeling/core_extension.ipynb
docs/tutorials/data-modeling/http_purl.org_cognite_neat_data-model_verified_physical_neat_playground_NeatHelloWorld_v1.html
docs/tutorials/data-modeling/http_purl.org_cognite_neat_data-model_verified_physical_sp_doctrino_space_ExtensionCore_v1.html

https://cognite-neat.readthedocs-hosted.com/en/latest/tutorials/data-modeling/cold_start.html#inspect-model
https://cognite-neat.readthedocs-hosted.com/en/latest/tutorials/data-modeling/core_extension.html#creating-the-base-model
In the tutorials we overwrite the HTML for the models. I think we should have unique names for the html files per model.

Unique HTML name

---

cognite/neat/_rules/exporters/_rules2excel.py
cognite/neat/_session/_state.py
cognite/neat/_session/_to.py
docs/CHANGELOG.md
docs/tutorials/data-modeling/core_extension.ipynb

[NEAT-640] 🥺Dump Excel with Reference

---

cognite/neat/_graph/transformers/_rdfpath.py
docs/CHANGELOG.md
tests/tests_unit/graph/test_transformers/test_make_connection_on_exact_match.py

[NEAT-662] 🐛 Exact Match Issue

---

cognite/neat/_utils/auth.py
docs/CHANGELOG.md

[NEAT-670]  Fallback to cwd if not in repo

---

cognite/neat/_graph/extractors/_classic_cdf/_base.py
cognite/neat/_graph/extractors/_classic_cdf/_sequences.py
cognite/neat/_issues/warnings/_external.py
cognite/neat/_session/_inspect.py
cognite/neat/_session/_read.py
cognite/neat/_store/_graph_store.py
docs/CHANGELOG.md
tests/tests_unit/graph/test_extractors/test_sequences_extractor.py

[NEAT-679] 🛑 Warning for lack of acccess

---

poetry.lock
pyproject.toml

No longer needed after workflows and service are removed.

Cleanup depedencies

---

cognite/neat/_graph/extractors/_classic_cdf/_classic.py
cognite/neat/_issues/errors/_resources.py
cognite/neat/_session/_inspect.py
cognite/neat/_session/_read.py
cognite/neat/_session/_state.py
cognite/neat/_store/_rules_store.py

[NEAT-703] 🧑‍✈️ Classic to snapshot

---

cognite/neat/_constants.py
cognite/neat/_graph/queries/_base.py
cognite/neat/_graph/transformers/_value_type.py
cognite/neat/_session/_base.py
docs/CHANGELOG.md

- Initiating NeatSession will automatically select the best possible graph storage
- Form of internal neat data model

🎛 Auto select store neat ontology

---

cognite/neat/_session/_base.py
cognite/neat/_session/_create.py
cognite/neat/_session/_prepare.py
docs/reference/NeatSession/create.md
docs/tutorials/data-modeling/core_extension.ipynb
docs/tutorials/data-onboarding/classic_knowledge_graph.ipynb
tests/tests_end_to_end/test_rules_flow.py
tests/tests_integration/test_session/test_graph_flow.py
tests/tests_integration/test_session/test_read.py

Moving from the .prepare to new .create API

💁Create API

---

cognite/neat/_graph/queries/_base.py
cognite/neat/_issues/errors/__init__.py
cognite/neat/_issues/errors/_external.py
cognite/neat/_session/_base.py
cognite/neat/_session/_state.py
cognite/neat/_session/exceptions.py
cognite/neat/_store/_graph_store.py
docs/CHANGELOG.md

Main issue, I cannot get a nice printout of error when oxi is locked
it is suppose to print out error and fix that are defined in `OxigraphStorageLockedError`

🥏 Public interface for on disc oxi

---

cognite/neat/_rules/importers/_rdf/_inference2rules.py
cognite/neat/_session/_base.py
docs/CHANGELOG.md
docs/tutorials/data-modeling/cold_start.ipynb
tests/tests_integration/test_session/test_graph_flow.py
tests/tests_integration/test_session/test_graph_flow/test_dexpi_to_dms.yml

[NEAT-721] 🏎 Inference

---

cognite/neat/_rules/exporters/_rules2excel.py
cognite/neat/_session/_to.py
cognite/neat/_utils/spreadsheet.py
docs/CHANGELOG.md

👻 Auto hide internal columns when exporting Rules as spreadsheets

---

docs/tutorials/data-modeling/core_extension.ipynb

updated drop method in tutorial

[NEAT-748] Updated drop method in tutorial - Update core_extension.ipynb

---

cognite/neat/_rules/analysis/_base.py
cognite/neat/_session/_show.py
docs/CHANGELOG.md
tests/tests_integration/test_session/test_data_model_to.py

- move information/dms rules di graph generation under analysis
- fixed issue with information dm not being rendered
before
after

🛻 Neat 762 move di graph to analysis

---

cognite/neat/_issues/_factory.py
cognite/neat/_rules/_constants.py
cognite/neat/_rules/models/data_types.py
cognite/neat/_rules/models/dms/_rules.py
cognite/neat/_rules/models/entities/_single_value.py
docs/CHANGELOG.md
tests/tests_integration/test_session/test_graph_flow.py
tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_to_python.yml
tests/tests_unit/rules/test_models/test_entities.py

- Support for less restrictive edge type
- Setting of proper value type for default
- Errors that do not have loc are now well handled in neat session

Neat 786 no restriction on edge type

---

cognite/neat/_session/_fix.py
cognite/neat/_session/_subset.py
docs/reference/NeatSession/fix.md
docs/reference/NeatSession/set.md
docs/reference/NeatSession/subset.md
mkdocs.yml

Added missing API documentation. This is a pure docs + docstring update.

[NEAT-802] 📕 Add missing docs

---

.github/workflows/code-quality.yaml

👾ci: fix running job

---

cognite/neat/_session/_base.py
cognite/neat/_session/_read.py
cognite/neat/_session/_state.py
cognite/neat/_session/_to.py

Friendly error message if conditions are not met in NeatSession when users are trying to execute public methods such as:
- NeatSession state checks prior execution of NeatSession methods. Checks are currently performed for existence of client, whether data model and instance store are empty or not

Friendly error message if conditions are not met in NeatSession

---

tests/tests_unit/rules/test_models/test_entities.py
tests/tests_unit/rules/test_models/test_information_rules.py

We have not needed this functionality before now. Adding tests to verify that it works as intended.

[NEAT-828] 👋 Class entities support version

---

mkdocs.yml

Tutorials which demonstrate how to populate DM using neat have been removed from docs. 
- Tutorials which demonstrate how to populate DM using neat have been removed from docs.

remove dm population except for migration

---

scripts/dependency_profiler.py

**RISK REVIEWER**: A helper not part of the code base. 
Example output

Dependency profiler

---

cognite/neat/_state/README.md

This is part of a refactoring to NeatState, https://github.com/cognitedata/neat/pull/1077.
It is a pure documentation showing the intended flow of the state machine implemented in NeatState.

[NEAT-885] 📃 Document state machine

---

cognite/neat/_graph/loaders/__init__.py
cognite/neat/_graph/loaders/_base.py
cognite/neat/_graph/loaders/_rdf2dms.py
cognite/neat/_graph/loaders/_rdf_to_instance_space.py
tests/tests_unit/test_graph/test_loaders/test_rdf_to_instance_space.py

Move out the logic for creating an instance space.

[prep NEAT-806] 👷Move out space instance logic from DMS Loader

---

cognite/neat/_graph/loaders/_rdf2dms.py
cognite/neat/_graph/loaders/_rdf_to_instance_space.py
cognite/neat/_session/_to.py
tests/tests_integration/test_session/test_graph_flow.py
tests/tests_unit/test_graph/test_loaders/test_dms_loader.py
tests/tests_unit/test_graph/test_loaders/test_rdf2dms.py
tests/tests_unit/test_rules/test_importers/test_inference_importer.py

[prep NEAT-806 part 2] 👷Update DMSLoader with InstanceSpaceLoader

---

.github/workflows/code-quality.yaml

ci: trigger neat-migration

---

cognite/neat/_session/_to.py

[NEAT-806] 👻 Explicit creation of instance spaces

---

cognite/neat/_client/data_classes/location_filters.py
cognite/neat/_graph/loaders/__init__.py
cognite/neat/_graph/loaders/_to_location_filter.py
tests/tests_unit/test_graph/test_loaders/test_location_filter_loader.py

[NEAT-755] 🦿 Location filter loader

---

cognite/neat/_session/_to.py

Adding `neat.to.cdf.location_filter()`.

[NEAT-755] 👀 Location filter in Session

---

cognite/neat/_graph/extractors/_dms.py
cognite/neat/_graph/extractors/_instances.py
tests/tests_integration/test_session/test_graph_flow.py

Needed to refactor for reuse in view extactor

[prep NEAT-909]🪟 Refactor out InstanceExtractor from DMSExtractor

---

cognite/neat/_graph/extractors/__init__.py
cognite/neat/_graph/extractors/_dms.py
cognite/neat/_graph/extractors/_views.py
tests/tests_unit/test_graph/test_extractors/test_view_extractor.py

[prep NEAT-909]🪟 View Extractor

---

cognite/neat/_session/_read.py
tests/tests_integration/test_session/test_read.py

[NEAT-909]🪟 Read single view

---

scripts/one_off/__init__.py
scripts/one_off/illformed_model_to_conceptual.py

[NEAT-913] 🧑‍🎨 Custom script for translation

---

pyproject.toml
scripts/one_off/translate_model.py
uv.lock

One-off script for translation

[NEAT-911] 🧑‍💻 Language translation

---

cognite/neat/_graph/extractors/__init__.py
cognite/neat/_graph/extractors/_extractor_mapping.py
tests/tests_unit/test_graph/test_extractors/test_extractor_mapping.py

[prep NEAT-914] 🗺 Extractor mapper

---

cognite/neat/_rules/models/_base_input.py
cognite/neat/_utils/mapping.py
tests/tests_unit/test_utils/test_mapping.py

Utility function for conversion from conceptual to mappings.

[prep NEAT-914] 🌍 Utils for conceptual to mapping

---

cognite/neat/_graph/extractors/__init__.py
cognite/neat/_graph/extractors/_unknown_namespace_extractor_mapper.py
tests/tests_unit/test_graph/test_extractors/test_unknown_namespace_extractor_mapper.py

When extracting instances we typically do not know the spaces ahead of time.

[prep NEAT-914] 🌏 Namespace free mapper

---

cognite/neat/_utils/mapping.py
tests/tests_unit/test_utils/test_mapping.py

[prep NEAT-914] 🤧 Extend helper methods

---

cognite/neat/_session/_read.py

Read view with mapping of new properties. Skipped automated test as this feature is unlikely to go into the main package. Instead, tested manually on customer data.

[NEAT-914] 🚎 Read view with mapping

---

cognite/neat/_graph/transformers/__init__.py
cognite/neat/_graph/transformers/_best_class_match.py
tests/tests_unit/test_graph/test_transformers/test_best_class_match.py

Adds a graph transformer that sets the `'RDF.type` based on minimizing the number of lost properties, if the

[prep NEAT-915]🏟BestClassMatch Transformer

---

cognite/neat/_session/_read.py
cognite/neat/_utils/read.py
tests/tests_unit/test_utils/test_read.py

[prep NEAT-915] 🏗 Refactor move out conceptual model read

---

cognite/neat/_session/_set.py

Set the `RDF.type` based on best match with given classes.

[NEAT-915] 🏛 Best matching class

---

cognite/neat/_graph/transformers/_best_class_match.py
cognite/neat/_issues/warnings/__init__.py
cognite/neat/_issues/warnings/_instances.py
tests/tests_unit/test_graph/test_transformers/test_best_class_match.py

The `GROUP_CONCAT` does not seem to be implemented on `oxigraph`. Reimplementing using describe instead.

[NEAT-915] 🗻 Rewriting BestClassMatchTransformer for oxigraph

---

cognite/neat/_graph/transformers/_best_class_match.py
cognite/neat/_issues/warnings/__init__.py
cognite/neat/_issues/warnings/_instances.py

Bug in min logic. In addition, warning if multi class fit.

[NEAT-915]🌋 Bughunt class matching

---

cognite/neat/_graph/extractors/__init__.py
cognite/neat/_graph/extractors/_exclude.py
tests/tests_unit/test_graph/test_extractors/test_exclude_extractor.py

Extractor for excluding predicates in the extraction

[prep NEAT-921] 🏕 Exclude extractor

---

cognite/neat/_session/_read.py

[NEAT-921] 🏝 Add exclude option

---

.github/workflows/code-quality.yaml
.github/workflows/release-experimental.yaml
cognite/neat/_experimental/_flags.py

Test Experimental
- My change.

NEAT Experimental test

---

cognite/neat/_graph/queries/_select.py
tests/tests_unit/test_graph/test_queries/test_select.py

Add cardinality explore properties

[prep NEAT-916] 🤓 Add cardinality explore properties

---

.github/workflows/release-experimental.yaml

[EXPERIMENTAL] Fix release workflow

---

cognite/neat/_graph/transformers/_best_class_match.py

🐛 Fix introduced bug

---

cognite/neat/_rules/models/entities/_wrapped.py
dev.py
tests/tests_unit/test_neat_package_metadata.py
tests/tests_unit/test_rules/test_models/test_wrapped_entities.py

[EXPERIMENTAL] Merge main

---

scripts/one_off/report_best_class_match.py

[NEAT-916] 🤔 Implement custom script best match

---

cognite/neat/_graph/extractors/_dict.py
tests/tests_unit/test_graph/test_extractors/test_dict_extractor.py

Need to write empty as we use the predicates to classify each instance.

[NEAT-916] 🕳 Explicit write empty

---

.github/workflows/release-experimental.yaml

- Release test experimental version

bump experimental version

---

.github/workflows/release-experimental.yaml

- Fixed experimental release tag

fix tag in experimental workflow

---

.github/workflows/release-experimental.yaml

- Make experimental versioning semver compliant

fix versioning

---

.github/workflows/release-experimental.yaml

match PEP 440

---

.github/workflows/release-experimental.yaml

Fix experimental env
- Fix experimental env

fix workflow enviroment

---

cognite/neat/_graph/loaders/__init__.py
cognite/neat/_graph/loaders/_table.py
tests/tests_unit/test_graph/test_loaders/test_dict_loader.py

[prep NEAT-946]  Dict loader

---

cognite/neat/_session/_to.py

`neat.to.file.instances.parquet()`

[NEAT-946] 😇 Expose to writing to parquet

---

cognite/neat/_graph/loaders/_table.py
tests/tests_unit/test_graph/test_loaders/test_dict_loader.py

[NEAT-946] 👷 Fix issues

---

pyproject.toml
uv.lock

Prep to pull in the valuable from clustering.

🏹; added Pyarrow

---

tests/tests_unit/test_graph/test_loaders/test_dict_loader.py

fix: bug in test

---

cognite/neat/core/_rules/importers/__init__.py
cognite/neat/core/_rules/importers/_spreadsheet2rules.py

Removed GoogleSheetImporter as this was an experimental internal feature, unused. Maybe this could be reintroduced properly to NEAT if needed. 
- Removed GoogleSheetImporter as this was an experimental internal feature, unused.

remove google spreadsheet importer

---

cognite/neat/session/_to.py

Allow to set instance spaces directly.

[NEAT-917] 👷 Allow specify instance spaces

---

cognite/neat/session/_set.py

🐛Fix set type by instance ID

---

scripts/one_off/properties_to_conceptual.py
scripts/one_off/translate_model.py

[NEAT-974] 🤓 Script properties to conceptual

---

cognite/neat/session/_mapping.py
tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_ids_to_python.yml
tests/tests_integration/test_session/test_graph_flow/test_snapshot_workflow_to_python.yml

🐛Fix label tag conversion

---

cognite/neat/core/_data_model/transformers/_converters.py
tests/tests_unit/test_rules/test_transformers/test_merge_dms_models.py

🐛Fix MergeDMSRules

---

cognite/neat/core/_data_model/models/information/_rules.py
tests/tests_integration/test_session/test_graph_flow/test_create_extension_template.yml

Make make count int if possible

🔢 Max count int if possible

---

cognite/neat/core/_data_model/transformers/__init__.py
cognite/neat/core/_data_model/transformers/_converters.py
cognite/neat/core/_data_model/transformers/_merge_conceptual.py
tests/tests_unit/test_rules/test_transformers/test_merge_conceptual.py

Update the Conceptual Model Merger to take some of the responsibility from the GraphImporter

[prep NEAT-920]👐Merge conceptual models

---

cognite/neat/core/_data_model/importers/_merge_importer.py
cognite/neat/core/_data_model/transformers/__init__.py
cognite/neat/core/_data_model/transformers/_converters.py
cognite/neat/core/_data_model/transformers/_merge_physical.py
tests/tests_unit/test_rules/test_transformers/test_merge_dms_models.py

Careful implementation of merging of physical model

[prep NEAT-920]🙏Merge physical models

---

cognite/neat/core/_data_model/importers/__init__.py
cognite/neat/core/_data_model/importers/_import_transform.py
tests/tests_unit/test_rules/test_importers/test_conceptual_transform_importer.py

[prep NEAT-888] 🦾Transform importer

---

cognite/neat/core/_instances/loaders/_rdf_to_instance_space.py

🐛Fix instance space loader

---

cognite/neat/session/_base.py
tests/tests_end_to_end/test_connect_data.py

Create the connection between existing data model and data.

[NEAT-920, (NEAT-661)] 🔗 Connect data to existing data model

---

cognite/neat/session/_to.py

feat; added data model to Python

---

cognite/neat/core/_data_model/transformers/__init__.py
cognite/neat/core/_data_model/transformers/_conceptual_property_renaming.py
tests/tests_unit/test_rules/test_transformers/test_conceptual_property_renaming.py

[prep NEAT-972] Conceptual mapper

---

cognite/neat/core/_client/data_classes/schema.py
cognite/neat/session/_base.py
tests/tests_end_to_end/test_connect_data.py

Renaming of connection parent to asset. This is necessary when a asset is converted to equipment.

[NEAT-972] 🔗 Update connection

---

cognite/neat/core/_utils/tarjan.py
tests/tests_unit/test_utils/test_tarjan.py

Add strongly connected algorithm.

---

scripts/one_off/properties_to_conceptual.py
scripts/one_off/translate_model.py

refactor: update scripts

---

cognite/neat/core/_instances/queries/_select.py

The queries does not properly filter out the RDF.type.

🐛Fix filter out rdf type

---

cognite/neat/core/_instances/transformers/__init__.py
cognite/neat/core/_instances/transformers/_object_mapper.py
tests/tests_unit/test_graph/test_transformers/test_object_mapper.py

[prep NEAT-998]  Object mapper

---

cognite/neat/session/_drop.py

Handle when you drop something not in the GraphDB

fix: handle not in db

---

cognite/neat/session/exceptions.py

This helps the IDE understand how to navigate the NeatSession.

Session type hint

---

cognite/neat/core/_client/_api/crud.py
cognite/neat/core/_client/_deploy.py
cognite/neat/core/_client/data_classes/deploy_differences.py
cognite/neat/core/_client/data_classes/deploy_result.py
tests/tests_unit/test_neat_client/test_crud_api.py
tests/tests_unit/test_neat_client/test_deploy.py
tests/utils.py

Implement the CRUD for containers. Introduce the merging of containers.

[prep NEAT-1018] Container CRUD

---

cognite/neat/core/_client/_api/crud.py
cognite/neat/core/_client/data_classes/deploy_result.py
cognite/neat/session/notebook_visualization/deploy_report.py

[NEAT-1021] UI interface

---

scripts/one_off/translate_model.py

refactor: added new translation method

---

cognite/neat/core/_data_model/models/physical/_exporter.py
tests/tests_unit/test_rules/test_exporters/test_rules2dms.py
tests/tests_unit/test_rules/test_models/test_physical_data_model.py

[NEAT-1024] 😵Default limit

---

cognite/neat/core/_client/_api/extended_data_modeling.py
cognite/neat/core/_client/_api_client.py
cognite/neat/core/_client/data_classes/instances.py
cognite/neat/core/_client/utils/_concurrency.py
cognite/neat/core/_client/utils/_http_client.py
cognite/neat/core/_constants.py

Fast method that takes advantage of up to 4 workers when writing instances.

🚄Added apply fast method

---

cognite/neat/core/_instances/loaders/_rdf2dms.py

Using the apply_fast method  in the DMSLoader

😃 Use fast apply

---

cognite/neat/core/_utils/producer_worker.py
tests/tests_unit/test_utils/test_producer_worker.py

Worker producer

---

cognite/neat/core/_utils/producer_worker.py

feat: allow no iteration count

---

cognite/neat/core/_instances/loaders/_rdf2dms.py
cognite/neat/core/_store/_instance.py

Handling invalid

---

cognite/neat/core/_data_model/_constants.py
cognite/neat/core/_data_model/models/conceptual/_validation.py
tests/tests_unit/test_rules/test_models/test_entities.py

This is first of multiple stacked PRs that are dealing with relaxation of conceptual data model, which aim at lossless importing and inferring of conceptual data model.
- Reduce concept id regex restriction allowing additional characters

Relax regex on concept id

---

.gemini/config.yaml
.gemini/styleguide.md

🧑‍🏫Add gemini configuration

---

cognite/neat/session/_session/_data_model/_read.py
tests/tests_integration/test_session/test_read.py
tests/tests_integration/test_session/test_read/test_read_cdm.yml

Added missing CDF reader endpoint
- CDF reader endpoint

Add missing CDF reader endpoint

---

.github/workflows/code-quality.yaml
.github/workflows/release.yaml

Adds Codecov. This enables reviewers to see exactly how test coverage changes as a result of a PR as well as which lines are hit.

[THIS-749] 🌐 Set up codecov

---

.github/CODEOWNERS
.github/workflows/code-quality.yaml

This should take care of the following noise in PRs:

[THIS-750] 😃 Update CI

---

.github/CODEOWNERS

This repo is now moved to the accelerate team.

🪦RIP iknow

---

tests/tests_unit/test_data_model/test_models/test_dms/test_containers.py
tests/tests_unit/test_data_model/test_models/test_dms/test_space.py

Introduce testing for container and space `as_request`.

[THIS-754] 🤓 As request tests

---

cognite/neat/_data_model/models/dms/__init__.py
cognite/neat/_data_model/models/dms/_base.py
cognite/neat/_data_model/models/dms/_constraints.py
cognite/neat/_data_model/models/dms/_data_types.py
cognite/neat/_data_model/models/dms/_indexes.py
cognite/neat/_data_model/models/dms/_types.py
cognite/neat/_data_model/models/dms/_view_property.py
tests/tests_unit/test_data_model/test_models/test_dms/strategies.py
tests/tests_unit/test_data_model/test_models/test_dms/test_containers.py
tests/tests_unit/test_data_model/test_models/test_dms/test_views.py

Context We are in the process of reimplementing the core part of Neat. The previous PRs have introduced a new internal structure (1-to-1 with API) for DMS classes.
I have started to use the newly created pydantic classes for the DMS API in #1323. I found several issues that are fixed with this PR.
**Note**: This code has not yet been released thus no release is necessary.

[THIS-773] 👷‍♂️ Added fixes to DMS pydantic
